# Generated by Django 2.2.3 on 2019-07-27 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featuredId',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
